CharityTestCore/CharityTestCore/Controllers/EPTTestController.cs
using CharityTestCore.Models;
using CharityTestCore.Service;
using CharityTestCore.Service.EPT;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CharityTestCore.Controllers
{
	public class EPTTestController : BaseController
	{
		protected IEPTService eptservice;
		public EPTTestController(IEPTService _eptservice)
		{
			eptservice = _eptservice;
		}
		// GET: EPTTest
		[Authorize]
		public IActionResult Index()
		{
			return View();
		}
		[HttpGet]
		[Authorize]

		public IActionResult RegisterEptQuestion()
		{
			ViewBag.Title = "آزمون  ";

			//ViewBag.EPTQuiz = new CharityTestCoreService().EptQuizTextList();
			return View(new EPTQuestion());
		}
		[HttpPost]
		[Authorize]

		public IActionResult RegisterEptQuestion(EPTQuestion ePTQuestion)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			var result = 0;

			result = eptservice.AddEptQuestion(OnGetUserId(), ePTQuestion.HaveSkill, ePTQuestion.BeforeYouHaveJob, ePTQuestion.DoYouWantHaveJob,
				ePTQuestion.S01,
				ePTQuestion.S02,
				ePTQuestion.S03,
				ePTQuestion.S04,
				ePTQuestion.S05,
				ePTQuestion.S06,
				ePTQuestion.S07,
				ePTQuestion.S08,
				ePTQuestion.S09,
				ePTQuestion.S10,
				ePTQuestion.S11,
				ePTQuestion.S12,
				ePTQuestion.S13,
				ePTQuestion.S14,
				ePTQuestion.S15,
				ePTQuestion.S16,
				ePTQuestion.S17,
				ePTQuestion.S18,
				ePTQuestion.S19,
				ePTQuestion.S20,
				ePTQuestion.S21,
				ePTQuestion.S22,
				ePTQuestion.S23,
				ePTQuestion.S24,
				ePTQuestion.S25,
				ePTQuestion.S26,
				ePTQuestion.S27,
				ePTQuestion.S28,
				ePTQuestion.S29,
				ePTQuestion.S30,
				ePTQuestion.S31,
				ePTQuestion.S32,
				ePTQuestion.S33,
				ePTQuestion.S34,
				ePTQuestion.S35,
				ePTQuestion.S36,
				ePTQuestion.S37,
				ePTQuestion.S38,
				ePTQuestion.S39,
				ePTQuestion.S40,
				ePTQuestion.S41,
				ePTQuestion.S42,
				ePTQuestion.S43,
				ePTQuestion.S44,
				ePTQuestion.S45,
				ePTQuestion.S46,
				ePTQuestion.S47,
				ePTQuestion.S48,
				ePTQuestion.S49,
				ePTQuestion.S50,
				ePTQuestion.S51,
				ePTQuestion.S52,
				ePTQuestion.S53,
				ePTQuestion.S54,
				ePTQuestion.S55,
				ePTQuestion.S56,
				ePTQuestion.S57,
				ePTQuestion.S58,
				ePTQuestion.S59,
				ePTQuestion.S60,
				ePTQuestion.S61,
				ePTQuestion.S62,
				ePTQuestion.S63,
				ePTQuestion.S64,
				ePTQuestion.S65,
				ePTQuestion.S66,
				ePTQuestion.S67,
				ePTQuestion.S68,
				ePTQuestion.S69,
				ePTQuestion.S70,
				ePTQuestion.S71,
				ePTQuestion.S72,
				ePTQuestion.S73,
				ePTQuestion.S74,
				ePTQuestion.S75,
				ePTQuestion.S76,
				ePTQuestion.S77,
				ePTQuestion.S78,
				ePTQuestion.S79,
				ePTQuestion.S80,
				ePTQuestion.S81,
				ePTQuestion.S82,
				ePTQuestion.S83,
				ePTQuestion.S84,
				ePTQuestion.S85,
				ePTQuestion.S86,
				ePTQuestion.S87,
				ePTQuestion.S88,
				ePTQuestion.S89,
				ePTQuestion.S90,
				ePTQuestion.S91,
				ePTQuestion.S92,
				ePTQuestion.S93,
				ePTQuestion.S94,
				ePTQuestion.S95
			   );

			if (result == -1)
			{
				ViewBag.ErrorMessage = "در ذخیره سازی کاربر مشکلی رخ داده است. لطفا مجددا تلاش نمایید";
				return View();
			}
			else
				///ePTQuestion.NationalCode;
				return View("AnswerEptQuestion");


		}

		[HttpGet]
		public IActionResult RegisterEptQuestionV2()
		{

            if (eptservice.GetEptByUserId(OnGetUserId()) != null)
            {
				return RedirectToAction("UserProfile","Dashboard");
            }
            ViewBag.Title = "آزمون  ";

			//ViewBag.EPTQuiz = new CharityTestCoreService().EptQuizTextList();
			return View();
		}
		public class UserModel
		{
			public int Id { get; set; }
			public byte Name { get; set; }
		}
		[HttpPost]
		public IActionResult RegisterEptQuestionV2(List<UserModel> listofusers)
		{
            if (eptservice.GetEptByUserId(OnGetUserId()) != null)
            {
                return RedirectToAction("UserProfile", "Dashboard");
            }
            var result = eptservice.AddEptQuestion(OnGetUserId(), true, true, true,
				   listofusers[1].Name,
				   listofusers[2].Name,
				   listofusers[3].Name,
				   listofusers[4].Name,
				   listofusers[5].Name,
				   listofusers[6].Name,
				   listofusers[7].Name,
				   listofusers[8].Name,
				   listofusers[9].Name,
				   listofusers[10].Name,
				   listofusers[11].Name,
				   listofusers[12].Name,
				   listofusers[13].Name,
				   listofusers[14].Name,
				   listofusers[15].Name,
				   listofusers[16].Name,
				   listofusers[17].Name,
				   listofusers[18].Name,
				   listofusers[19].Name,
				   listofusers[20].Name,
				   listofusers[21].Name,
				   listofusers[22].Name,
				   listofusers[23].Name,
				   listofusers[24].Name,
				   listofusers[25].Name,
				   listofusers[26].Name,
				   listofusers[27].Name,
				   listofusers[28].Name,
				   listofusers[29].Name,
				   listofusers[30].Name,
				   listofusers[31].Name,
				   listofusers[32].Name,
				   listofusers[33].Name,
				   listofusers[34].Name,
				   listofusers[35].Name,
				   listofusers[36].Name,
				   listofusers[37].Name,
				   listofusers[38].Name,
				   listofusers[39].Name,
				   listofusers[40].Name,
				   listofusers[41].Name,
				   listofusers[42].Name,
				   listofusers[43].Name,
				   listofusers[44].Name,
				   listofusers[45].Name,
				   listofusers[46].Name,
				   listofusers[47].Name,
				   listofusers[48].Name,
				   listofusers[49].Name,
				   listofusers[50].Name,
				   listofusers[51].Name,
				   listofusers[52].Name,
				   listofusers[53].Name,
				   listofusers[54].Name,
				   listofusers[55].Name,
				   listofusers[56].Name,
				   listofusers[57].Name,
				   listofusers[58].Name,
				   listofusers[59].Name,
				   listofusers[60].Name,
				   listofusers[61].Name,
				   listofusers[62].Name,
				   listofusers[63].Name,
				   listofusers[64].Name,
				   listofusers[65].Name,
				   listofusers[66].Name,
				   listofusers[67].Name,
				   listofusers[68].Name,
				   listofusers[69].Name,
				   listofusers[70].Name,
				   listofusers[71].Name,
				   listofusers[72].Name,
				   listofusers[73].Name,
				   listofusers[74].Name,
				   listofusers[75].Name,
				   listofusers[76].Name,
				   listofusers[77].Name,
				   listofusers[78].Name,
				   listofusers[79].Name,
				   listofusers[80].Name,
				   listofusers[81].Name,
				   listofusers[82].Name,
				   listofusers[83].Name,
				   listofusers[84].Name,
				   listofusers[85].Name,
				   listofusers[86].Name,
				   listofusers[87].Name,
				   listofusers[88].Name,
				   listofusers[89].Name,
				   listofusers[90].Name,
				   listofusers[91].Name,
				   listofusers[92].Name,
				   listofusers[93].Name,
				   listofusers[94].Name,
				   listofusers[95].Name

				 );

			return Json(new
			{
                result = true
			});
		}
		public IActionResult AnswerEptQuestion()
		{
			return View();
		}
	}
}

CharityTestCore/CharityTestCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CharityTestCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CharityTestCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CharityTestCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CharityTestCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CharityTestCore/CharityTestCore/Views/Shared/_LayoutAdminSimple.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>پنل    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="../../plugins/datatables/dataTables.bootstrap4.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- bootstrap rtl -->
    <link rel="stylesheet" href="../../dist/css/bootstrap-rtl.min.css">
    <!-- template rtl version -->
    <link rel="stylesheet" href="../../dist/css/custom-style.css">
    <!-- AdminLTE for demo purposes -->


</head>
<body class="hold-transition sidebar-mini text-sm">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-light bg-light shadow-sm">
            <!-- Left navbar links -->
            <!-- Left menu toggle -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fa fa-bars"></i></a>
                </li>
            </ul>



            <!-- Right links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link"><i class="fa fa-home"></i> خانه</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Logout", "Account")" class="nav-link text-danger"><i class="fa fa-sign-out"></i> خروج</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
                <a href="#" class="brand-link" data-widget="pushmenu">
                <img src="../../dist/img/AdminLTELogo.png" alt="Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">پنل مدیریت</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <div>
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">   @RenderSection("ProfileName") </a>

                            @{
                                var firstName = User.FindFirst("FirstName")?.Value;
                                var lastName = User.FindFirst("LastName")?.Value;
                            }
                            @if (!string.IsNullOrEmpty(firstName) && !string.IsNullOrEmpty(lastName))
                            {
                                 <a href="#" class="d-block">سلام، @firstName @lastName</a>
                            }
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->

                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link active">
                                    <i class="nav-icon fa fa-table"></i>
                                    <p>
                                         
                                        <i class="fa fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a href="@Url.Action("Index", "Dashboard")" class="nav-link">
                                                <i class="fa fa-circle-o nav-icon"></i>
                                                <p>صفحه اصلی </p>
                                            </a>
                                        </li>

                                    <li class="nav-item">
                                        <a href="@Url.Action("ChangePassword", "Account")" class="nav-link">
                                            <i class="fa fa-circle-o nav-icon"></i>
                                            <p>تغییر رمز  عبور </p>
                                        </a>
                                    </li>
                            

                                </ul>
                              </li>
                          </ul>

                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
            <!-- /.sidebar -->
        </aside>


     
            <!-- Right navbar links -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1> </h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-left">
                        
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->

            <section class="content">

                @RenderSection("Body")


            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong> <a href=""></a>.</strong>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables -->
    <script src="../../plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../plugins/datatables/dataTables.bootstrap4.js"></script>
    <!-- SlimScroll -->
    <script src="../../plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="../../plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
@*     <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script> *@



    @RenderSection("script")


</body>
</html>

CharityTestCore/CharityTestCore/Views/Shared/_LayoutTest.cshtml
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>صفحه تست</title>
    @RenderSection("Head")
</head>
<body>
    @RenderSection("Body")

        @RenderSection("Scripts")


</body>

</html>

CharityTestCore/CharityTestCore/Views/Shared/_LayoutUserSimple.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>پنل کاربری</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="@Url.Content("~/plugins/datatables/dataTables.bootstrap4.css")" />
    <!-- Theme style -->
    <link rel="stylesheet" href="@Url.Content("~/dist/css/adminlte.min.css")" />
    <!-- Preconnect for Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=swap" rel="stylesheet">

    <!-- bootstrap rtl -->
    <link rel="stylesheet" href="@Url.Content("~/dist/css/bootstrap-rtl.min.css")" />
    <!-- template rtl version -->
    <link rel="stylesheet" href="@Url.Content("~/dist/css/custom-style.css")" />

</head>
<body class="hold-transition sidebar-mini layout-fixed text-sm">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-light bg-light shadow-sm">
            <!-- Left navbar links -->
            <!-- Left menu toggle -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fa fa-bars"></i></a>
                </li>
            </ul>



            <!-- Right links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link"><i class="fa fa-home"></i> خانه</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Logout", "Account")" class="nav-link text-danger"><i class="fa fa-sign-out"></i> خروج</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-7">
            <!-- Brand Logo -->
            <a href="#" class="brand-link bg-dark	" data-widget="pushmenu">
       
                <span class="brand-text font-weight-light">پنل کاربر</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <div>
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">   @RenderSection("ProfileName") </a>

                            @{
                                var firstName = User.FindFirst("FirstName")?.Value;
                                var lastName = User.FindFirst("LastName")?.Value;
                            }
                            @if (!string.IsNullOrEmpty(firstName) && !string.IsNullOrEmpty(lastName))
                            {
                                <a href="#" class="d-block">سلام، @firstName @lastName</a>
                            }
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->

                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link active">
                                    <i class="nav-icon fa fa-list-alt"></i>
                                    <p>
                                        مدیریت آزمون‌ها
                                        <i class="fa fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("RegisterEptQuestionV2", "EPTTest")" class="nav-link">
                                            <i class="fa fa-circle-o nav-icon"></i>
                                            <p>ثبت آزمون استعداد یابی</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("Quiz", "MBTIQuestion")" class="nav-link">
                                            <i class="fa fa-circle-o nav-icon"></i>
                                            <p>ثبت آزمون شخصیت</p>
                                        </a>
                                    </li>
@*                                     <li class="nav-item">
                                        <a href="@Url.Action("Quiz", "QuizQuestions")" class="nav-link">
                                            <i class="fa fa-circle-o nav-icon"></i>
                                            <p>ثبت آزمون دیسک</p>
                                        </a>
                                    </li> *@

                                </ul>
                            </li>

                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link ">
                                    <i class="nav-icon fa fa-cogs"></i>
                                    <p>
                                        تنظیمات کاربری
                                        <i class="fa fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <!-- آیتم: پروفایل من -->
                                    <li class="nav-item">
                                        <a href="@Url.Action("MyProfile", "Dashboard")" class="nav-link">
                                            <i class="fa fa-user nav-icon text-primary"></i>
                                            <p>پروفایل من</p>
                                        </a>
                                    </li>

                                    <!-- آیتم: تغییر رمز عبور -->
                                    <li class="nav-item">
                                        <a href="@Url.Action("ChangePassword", "Account")" class="nav-link">
                                            <i class="fa fa-key nav-icon text-danger"></i>
                                            <p>تغییر رمز عبور</p>
                                        </a>
                                    </li>
                                    @*                                     <li class="nav-item">
                                    <a href="@Url.Action("Quiz", "QuizQuestions")" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>ثبت آزمون دیسک</p>
                                    </a>
                                    </li> *@

                                </ul>
                            </li>
                


                        </ul>
                    </nav>

                    <!-- /.sidebar-menu -->
                </div>
            </div>
            <!-- /.sidebar -->
        </aside>



        <!-- Right navbar links -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1> </h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-left">
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->

            <section class="content">

                @RenderSection("Body")


            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong> <a href=""></a>.</strong>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-light">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- Scripts -->
    <script src="@Url.Content("~/plugins/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/plugins/bootstrap/js/bootstrap.bundle.min.js")"></script>
    <script src="@Url.Content("~/plugins/datatables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/plugins/datatables/dataTables.bootstrap4.js")"></script>
    <script src="@Url.Content("~/plugins/slimScroll/jquery.slimscroll.min.js")"></script>
    <script src="@Url.Content("~/plugins/fastclick/fastclick.js")"></script>
    <script src="@Url.Content("~/dist/js/adminlte.min.js")"></script>
@*     <script src="@Url.Content("~/dist/js/demo.js")"></script> *@

    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    @RenderSection("script")


</body>
</html>